version: "3.7"
services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: movies_test
    ports:
      - "5432:5432"
    volumes:
      - movie-db:/var/lib/postgresql/data

  api:
    build:
      context: .
    environment:
      DATABASE_URL: postgres://postgres:postgres@db:5432/movies_test
      PORT: 3000
    depends_on:
      - db
    ports:
      - "3000:3000"

volumes:
  movie-db:
